### ISSUE TITLE
Returned embbeded values

### ISSUE THREAD

**Issue by devarshml** [dkn22/embedder#3]
Hey, thanks for the wrapper.
Are the returned values after embedding sorted.
For example - the DayOfWeek column in rossman dataset can have values ranging from 1 to 7. So, after the embedding is done, i get a matrix which contains the embedded values, is it safe to assume that the first embedded value corresponds to DayOfWeek=1, second to DayOfWeek=2 and so on...

Thanks

**Comment by devarshml** [comment]
PFA

**Comment by dkn22** [comment]
@Devarsh-UTD if you call the get_embeddings() method you will get back a dictionary mapping embeddings to their categories.
